#!/usr/bin/env python2

from sys import argv, exit
from PIL import Image
from numpy import array
from scipy.cluster.vq import kmeans2

def clusterize(img, k):
    clusters, labels = kmeans2(array(img.getdata()).astype(float),
                               k, minit='points')
    img.putdata([tuple(map(int, clusters[label])) for label in labels])

def main():
    if len(argv) != 5:
        print('USAGE: %s [src] [dest] [k] [thumbnail size]' % argv[0])
        exit()

    _, src, dest, k, tsiz = argv
    k, tsiz = int(k), int(tsiz)

    img = Image.open(src)
    isiz = img.size
    img.thumbnail((tsiz, tsiz))
    clusterize(img, k)
    img = img.resize(isiz)
    img.save(dest)

if __name__ == '__main__':
    main()

