#!/usr/bin/env python2

from sys import argv, exit
from itertools import chain
from PIL import Image
from numpy import array
from scipy.cluster.vq import kmeans2
from colorsys import rgb_to_hsv, hsv_to_rgb

k = 2
tw = 200

def get_colors(img):
    w, h = img.size
    return list(chain(*(
        [color] * count for count, color in img.getcolors(w * h)
    )))

def clusterize(img, k):
    clusters, labels = kmeans2(array(img.getdata()), k, minit='points')
    img.putdata([tuple(clusters[label]) for label in labels])

def main():
    if len(argv) != 3:
        print('USAGE: %s [src] [dest]' % argv[0])
        exit()

    _, src, dest = argv

    img = Image.open(src)
    iw, ih = img.size

    thumb = img.copy()
    thumb.thumbnail((tw, tw * (ih / float(iw))))

    clusterize(thumb, k)
    rthumb = thumb.resize(img.size)

    rthumb.save(dest)

if __name__ == '__main__':
    main()
